[package]
name = "rock-paper-scissors"
version = "0.1.0"
authors = ["Paweł Romanowski <pawroman@gmail.com>"]

[dependencies]
lazy_static = "1.4.0"
rand = { version = "0.8.5", features = ["std_rng"] }
strum = "0.24.0"
strum_macros = "0.24.0"
